# Static Hong Kong travel data: attractions, hotels, transport

HK_ATTRACTIONS = [
    # ── Hong Kong Island ─────────────────────────────────────────────────────
    {
        "name": "Victoria Peak",
        "district": "The Peak / Central",
        "lat": 22.2759, "lng": 114.1455,
        "tags": ["scenic_views", "photography", "culture"],
        "cost_tier": "medium",
        "duration_hours": 2.5,
        "mobility_friendly": False,
        "crowd_level": "high",
        "description": "Iconic hilltop with panoramic city views; take the historic Peak Tram.",
        "opening": "Peak Tram 07:00-23:00 daily",
    },
    {
        "name": "PMQ",
        "district": "Central",
        "lat": 22.2817, "lng": 114.1536,
        "tags": ["culture", "photography", "social_trendy", "shopping"],
        "cost_tier": "low",
        "duration_hours": 1.5,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Former police married quarters turned creative hub with local designer shops and cafés.",
        "opening": "10:00-20:00 daily",
    },
    {
        "name": "Tai Kwun",
        "district": "Central",
        "lat": 22.2808, "lng": 114.1551,
        "tags": ["culture", "history", "photography", "social_trendy"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Restored Central Police Station complex now housing galleries, restaurants, and events.",
        "opening": "11:00-23:00 daily",
    },
    {
        "name": "Hong Kong Palace Museum",
        "district": "West Kowloon",
        "lat": 22.3033, "lng": 114.1578,
        "tags": ["culture", "history"],
        "cost_tier": "medium",
        "duration_hours": 3.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "World-class collection of Chinese art and artefacts from the Palace Museum Beijing.",
        "opening": "10:00-18:00 (closed Tue)",
    },
    {
        "name": "Stanley Market & Promenade",
        "district": "Stanley",
        "lat": 22.2185, "lng": 114.2121,
        "tags": ["shopping", "scenic_views", "local_food", "relaxation"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Charming seaside market village with alfresco dining and harbour views.",
        "opening": "10:00-18:00 daily",
    },
    {
        "name": "Repulse Bay Beach",
        "district": "Repulse Bay",
        "lat": 22.2366, "lng": 114.1964,
        "tags": ["scenic_views", "relaxation", "photography"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Scenic sandy beach with clear water, great for a relaxed afternoon.",
        "opening": "Open 24h",
    },
    {
        "name": "Nan Lian Garden",
        "district": "Diamond Hill",
        "lat": 22.3348, "lng": 114.2011,
        "tags": ["culture", "scenic_views", "relaxation", "photography"],
        "cost_tier": "low",
        "duration_hours": 1.5,
        "mobility_friendly": True,
        "crowd_level": "low",
        "description": "Serene Tang-dynasty style garden adjacent to Chi Lin Nunnery.",
        "opening": "07:00-21:00 daily",
    },
    {
        "name": "Kennedy Town Promenade",
        "district": "Kennedy Town",
        "lat": 22.2796, "lng": 114.1280,
        "tags": ["local_food", "social_trendy", "scenic_views", "hidden_gems"],
        "cost_tier": "low",
        "duration_hours": 1.5,
        "mobility_friendly": True,
        "crowd_level": "low",
        "description": "Trendy neighbourhood at the western tip of HK Island with cool cafés and sea views.",
        "opening": "Open 24h",
    },

    # ── Kowloon ──────────────────────────────────────────────────────────────
    {
        "name": "Tsim Sha Tsui Promenade (Avenue of Stars)",
        "district": "Tsim Sha Tsui",
        "lat": 22.2936, "lng": 114.1719,
        "tags": ["scenic_views", "photography", "relaxation"],
        "cost_tier": "low",
        "duration_hours": 1.5,
        "mobility_friendly": True,
        "crowd_level": "high",
        "description": "Waterfront promenade with Victoria Harbour views and nightly Symphony of Lights show.",
        "opening": "Open 24h (show 20:00 daily)",
    },
    {
        "name": "Mong Kok Street Markets (Ladies Market / Flower Market)",
        "district": "Mong Kok",
        "lat": 22.3193, "lng": 114.1694,
        "tags": ["shopping", "local_food", "hidden_gems", "social_trendy"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "high",
        "description": "Bustling street markets for bargain shopping, street food, and local atmosphere.",
        "opening": "12:00-23:00 daily",
    },
    {
        "name": "Yau Ma Tei Temple Street Night Market",
        "district": "Yau Ma Tei",
        "lat": 22.3104, "lng": 114.1712,
        "tags": ["local_food", "culture", "hidden_gems", "social_trendy"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Atmospheric night market with street food, fortune tellers, and Cantonese opera.",
        "opening": "18:00-23:00 daily",
    },
    {
        "name": "Kowloon Walled City Park",
        "district": "Kowloon City",
        "lat": 22.3325, "lng": 114.1884,
        "tags": ["history", "culture", "hidden_gems", "relaxation"],
        "cost_tier": "low",
        "duration_hours": 1.5,
        "mobility_friendly": True,
        "crowd_level": "low",
        "description": "Historic park on the site of the former Walled City; peaceful with informative exhibits.",
        "opening": "06:30-23:00 daily",
    },
    {
        "name": "Sham Shui Po Electronics & Fabric Markets",
        "district": "Sham Shui Po",
        "lat": 22.3299, "lng": 114.1628,
        "tags": ["shopping", "hidden_gems", "local_food"],
        "cost_tier": "low",
        "duration_hours": 2.0,
        "mobility_friendly": True,
        "crowd_level": "medium",
        "description": "Budget paradise for electronics, fabrics, and local eateries beloved by locals.",
        "opening": "10:00-20:00 daily",
    },

    # ── New Territories & Outlying Islands ──────────────────────────────────
    {
        "name": "Tian Tan Buddha (Big Buddha) & Po Lin Monastery",
        "district": "Lantau Island",
        "lat": 22.2537, "lng": 113.9055,
        "tags": ["culture", "history", "scenic_views", "photography"],
        "cost_tier": "medium",
        "duration_hours": 4.0,
        "mobility_friendly": False,
        "crowd_level": "high",
        "description": "World's largest outdoor seated bronze Buddha atop Lantau; stunning mountain scenery.",
        "opening": "Cable car 10:00-17:30; Buddha 10:00-17:00",
    },
    {
        "name": "Tai O Fishing Village",
        "district": "Lantau Island",
        "lat": 22.2541, "lng": 113.8649,
        "tags": ["culture", "hidden_gems", "local_food", "photography"],
        "cost_tier": "low",
        "duration_hours": 2.5,
        "mobility_friendly": True,
        "crowd_level": "low",
        "description": "Charming stilt-house village known for shrimp paste, seafood, and pink dolphin boat tours.",
        "opening": "Open daily",
    },
    {
        "name": "Sai Kung Waterfront & Seafood",
        "district": "Sai Kung",
        "lat": 22.3814, "lng": 114.2706,
        "tags": ["local_food", "scenic_views", "relaxation", "hidden_gems"],
        "cost_tier": "medium",
        "duration_hours": 3.0,
        "mobility_friendly": True,
        "crowd_level": "low",
        "description": "Picturesque harbour town famed for fresh live seafood restaurants and country park access.",
        "opening": "Open daily",
    },
]

HK_HOTELS = [
    # Low budget (~HKD 200-400/night)
    {
        "name": "Mei Ho House Youth Hostel",
        "area": "Sham Shui Po",
        "budget_tier": "low",
        "price_hkd_per_night": 280,
        "mtr_minutes": 1,
        "description": "Heritage hostel in a restored 1950s estate; great MTR access.",
    },
    {
        "name": "YHA Mei Ho House",
        "area": "Sham Shui Po",
        "budget_tier": "low",
        "price_hkd_per_night": 320,
        "mtr_minutes": 2,
        "description": "Clean, well-located budget option popular with student travellers.",
    },
    {
        "name": "Chungking Mansions Guesthouses",
        "area": "Tsim Sha Tsui",
        "budget_tier": "low",
        "price_hkd_per_night": 250,
        "mtr_minutes": 3,
        "description": "Iconic backpacker location in the heart of TST; basic but central.",
    },
    {
        "name": "Mini Hotel Central",
        "area": "Central",
        "budget_tier": "low",
        "price_hkd_per_night": 380,
        "mtr_minutes": 2,
        "description": "Compact, modern rooms in prime Central location.",
    },
    # Medium budget (~HKD 600-1000/night)
    {
        "name": "Ibis Hong Kong Central & Sheung Wan",
        "area": "Sheung Wan",
        "budget_tier": "medium",
        "price_hkd_per_night": 700,
        "mtr_minutes": 2,
        "description": "Reliable mid-range chain hotel near Central with good transport links.",
    },
    {
        "name": "Hotel Ease Mong Kok",
        "area": "Mong Kok",
        "budget_tier": "medium",
        "price_hkd_per_night": 650,
        "mtr_minutes": 1,
        "description": "Modern hotel in the heart of Mong Kok; excellent for night markets.",
    },
    {
        "name": "Silka Tsuen Wan Hong Kong",
        "area": "Tsuen Wan",
        "budget_tier": "medium",
        "price_hkd_per_night": 600,
        "mtr_minutes": 2,
        "description": "Comfortable hotel slightly outside the centre with great MTR access.",
    },
    {
        "name": "Dorsett Tsuen Wan",
        "area": "Tsim Sha Tsui",
        "budget_tier": "medium",
        "price_hkd_per_night": 850,
        "mtr_minutes": 1,
        "description": "Well-appointed hotel in TST, walking distance to the promenade.",
    },
    # High budget (~HKD 1500+/night)
    {
        "name": "The Peninsula Hong Kong",
        "area": "Tsim Sha Tsui",
        "budget_tier": "high",
        "price_hkd_per_night": 4500,
        "mtr_minutes": 5,
        "description": "Legendary luxury hotel with iconic harbour views and white-glove service.",
    },
    {
        "name": "Mandarin Oriental Hong Kong",
        "area": "Central",
        "budget_tier": "high",
        "price_hkd_per_night": 3800,
        "mtr_minutes": 3,
        "description": "Award-winning luxury in Central with world-class dining.",
    },
    {
        "name": "InterContinental Grand Stanford",
        "area": "Tsim Sha Tsui",
        "budget_tier": "high",
        "price_hkd_per_night": 2200,
        "mtr_minutes": 5,
        "description": "Luxury waterfront hotel with panoramic Victoria Harbour views.",
    },
]

# Daily per-person budget benchmarks (HKD)
BUDGET_TIERS = {
    "low": {
        "transport": 50,    # MTR day pass ~HKD 55
        "food": 100,        # local cha chaan teng + street food
        "activities": 30,   # mostly free attractions
        "misc": 20,
        "total_per_person": 200,
        "hotel_per_night": 300,  # shared/hostel
    },
    "medium": {
        "transport": 80,
        "food": 200,        # mix of local & casual restaurants
        "activities": 150,
        "misc": 70,
        "total_per_person": 500,
        "hotel_per_night": 750,
    },
    "high": {
        "transport": 150,   # taxis + ferry
        "food": 500,        # fine dining
        "activities": 400,
        "misc": 200,
        "total_per_person": 1250,
        "hotel_per_night": 3000,
    },
}

# District-level transport connections (MTR-centric, travel time in minutes)
TRANSPORT = {
    ("Central", "Tsim Sha Tsui"): {"mode": "MTR / Star Ferry", "minutes": 10, "cost_hkd": 10},
    ("Central", "Mong Kok"): {"mode": "MTR", "minutes": 15, "cost_hkd": 12},
    ("Central", "Causeway Bay"): {"mode": "MTR / Tram", "minutes": 12, "cost_hkd": 9},
    ("Central", "The Peak / Central"): {"mode": "Peak Tram", "minutes": 10, "cost_hkd": 59},
    ("Tsim Sha Tsui", "Mong Kok"): {"mode": "MTR", "minutes": 8, "cost_hkd": 8},
    ("Tsim Sha Tsui", "Yau Ma Tei"): {"mode": "MTR", "minutes": 5, "cost_hkd": 6},
    ("Tsim Sha Tsui", "West Kowloon"): {"mode": "Walk / Bus", "minutes": 15, "cost_hkd": 4},
    ("Mong Kok", "Sham Shui Po"): {"mode": "MTR", "minutes": 5, "cost_hkd": 6},
    ("Mong Kok", "Diamond Hill"): {"mode": "MTR", "minutes": 12, "cost_hkd": 10},
    ("Central", "Stanley"): {"mode": "Bus 6/6X", "minutes": 40, "cost_hkd": 10},
    ("Central", "Repulse Bay"): {"mode": "Bus 6/260", "minutes": 35, "cost_hkd": 10},
    ("Tsim Sha Tsui", "Lantau Island"): {"mode": "MTR + Cable Car", "minutes": 60, "cost_hkd": 250},
    ("Central", "Sai Kung"): {"mode": "MTR + Bus", "minutes": 60, "cost_hkd": 20},
    ("Central", "Kennedy Town"): {"mode": "MTR", "minutes": 15, "cost_hkd": 8},
    ("Central", "Kowloon City"): {"mode": "Bus / Ferry", "minutes": 30, "cost_hkd": 15},
    ("Causeway Bay", "Stanley"): {"mode": "Bus 40", "minutes": 30, "cost_hkd": 8},
}

INTEREST_TAGS = [
    "culture",
    "history",
    "scenic_views",
    "photography",
    "local_food",
    "shopping",
    "relaxation",
    "hidden_gems",
    "social_trendy",
]

CONSTRAINT_TAGS = [
    "avoid_long_walking",
    "avoid_many_location_changes",
    "avoid_crowds",
    "avoid_packed_schedule",
    "avoid_outdoor_heavy",
    "avoid_expensive",
]

# Hong Kong monthly climate data (based on HK Observatory averages)
# Each month has base stats and 3 daily_variations cycled across trip days.
HK_WEATHER_BY_MONTH = {
    1: {
        "name": "January", "season": "Winter",
        "temp_high_c": 18, "temp_low_c": 13, "humidity_pct": 72,
        "rain_probability_pct": 15, "uv_index": 4,
        "general_advisory": "Cool and dry — ideal sightseeing conditions. Light jacket for mornings and evenings.",
        "daily_variations": [
            {"condition": "Sunny",         "temp_delta": 1,  "rain_delta": -5},
            {"condition": "Partly Cloudy", "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Sunny",         "temp_delta": 1,  "rain_delta": -5},
        ],
    },
    2: {
        "name": "February", "season": "Winter",
        "temp_high_c": 18, "temp_low_c": 14, "humidity_pct": 80,
        "rain_probability_pct": 30, "uv_index": 4,
        "general_advisory": "Misty and humid — visibility may be low at times. Bring an extra layer.",
        "daily_variations": [
            {"condition": "Partly Cloudy", "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Overcast",      "temp_delta": -1, "rain_delta": 10},
            {"condition": "Misty",         "temp_delta": 0,  "rain_delta": 5},
        ],
    },
    3: {
        "name": "March", "season": "Spring",
        "temp_high_c": 21, "temp_low_c": 17, "humidity_pct": 82,
        "rain_probability_pct": 40, "uv_index": 6,
        "general_advisory": "Mild but unpredictable — light rain gear recommended. Transitional weather.",
        "daily_variations": [
            {"condition": "Cloudy",        "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Light Rain",    "temp_delta": -1, "rain_delta": 20},
            {"condition": "Partly Cloudy", "temp_delta": 1,  "rain_delta": -10},
        ],
    },
    4: {
        "name": "April", "season": "Spring",
        "temp_high_c": 25, "temp_low_c": 21, "humidity_pct": 84,
        "rain_probability_pct": 55, "uv_index": 7,
        "general_advisory": "Rainy season begins — umbrella essential. Warm and humid.",
        "daily_variations": [
            {"condition": "Cloudy with Showers", "temp_delta": -1, "rain_delta": 15},
            {"condition": "Partly Cloudy",        "temp_delta": 1,  "rain_delta": -10},
            {"condition": "Light Rain",            "temp_delta": 0,  "rain_delta": 10},
        ],
    },
    5: {
        "name": "May", "season": "Rainy Season",
        "temp_high_c": 29, "temp_low_c": 25, "humidity_pct": 84,
        "rain_probability_pct": 70, "uv_index": 9,
        "general_advisory": "Heavy rain season — waterproof shoes and umbrella essential. Very hot and humid.",
        "daily_variations": [
            {"condition": "Heavy Showers",      "temp_delta": -1, "rain_delta": 20},
            {"condition": "Partly Cloudy",       "temp_delta": 1,  "rain_delta": -15},
            {"condition": "Overcast with Rain",  "temp_delta": 0,  "rain_delta": 10},
        ],
    },
    6: {
        "name": "June", "season": "Monsoon",
        "temp_high_c": 31, "temp_low_c": 27, "humidity_pct": 83,
        "rain_probability_pct": 75, "uv_index": 10,
        "general_advisory": "Typhoon season begins — monitor HK Observatory warnings. Very hot with heavy rain.",
        "daily_variations": [
            {"condition": "Heavy Rain",    "temp_delta": -1, "rain_delta": 15},
            {"condition": "Thunderstorms", "temp_delta": -2, "rain_delta": 20},
            {"condition": "Partly Cloudy", "temp_delta": 1,  "rain_delta": -20},
        ],
    },
    7: {
        "name": "July", "season": "Summer",
        "temp_high_c": 32, "temp_low_c": 28, "humidity_pct": 83,
        "rain_probability_pct": 65, "uv_index": 11,
        "general_advisory": "Hottest month — typhoon risk and intense heat. Stay hydrated and check HK Observatory alerts daily.",
        "daily_variations": [
            {"condition": "Sunny & Hot",   "temp_delta": 1,  "rain_delta": -10},
            {"condition": "Thunderstorms", "temp_delta": -1, "rain_delta": 20},
            {"condition": "Cloudy & Hot",  "temp_delta": 0,  "rain_delta": 5},
        ],
    },
    8: {
        "name": "August", "season": "Summer",
        "temp_high_c": 32, "temp_low_c": 28, "humidity_pct": 83,
        "rain_probability_pct": 65, "uv_index": 11,
        "general_advisory": "Hot, humid, and typhoon risk — check HK Observatory alerts daily.",
        "daily_variations": [
            {"condition": "Hot & Humid",   "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Thunderstorms", "temp_delta": -1, "rain_delta": 20},
            {"condition": "Partly Cloudy", "temp_delta": 1,  "rain_delta": -15},
        ],
    },
    9: {
        "name": "September", "season": "Late Summer",
        "temp_high_c": 30, "temp_low_c": 26, "humidity_pct": 81,
        "rain_probability_pct": 55, "uv_index": 9,
        "general_advisory": "Still warm — typhoon season continues. Conditions improve gradually toward month-end.",
        "daily_variations": [
            {"condition": "Partly Cloudy",      "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Occasional Showers", "temp_delta": -1, "rain_delta": 15},
            {"condition": "Hot & Sunny",         "temp_delta": 1,  "rain_delta": -15},
        ],
    },
    10: {
        "name": "October", "season": "Autumn",
        "temp_high_c": 27, "temp_low_c": 23, "humidity_pct": 73,
        "rain_probability_pct": 25, "uv_index": 7,
        "general_advisory": "Best time to visit — clear skies, comfortable temperatures, and low humidity.",
        "daily_variations": [
            {"condition": "Sunny",          "temp_delta": 1,  "rain_delta": -5},
            {"condition": "Partly Cloudy",  "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Clear & Breezy", "temp_delta": -1, "rain_delta": -5},
        ],
    },
    11: {
        "name": "November", "season": "Autumn",
        "temp_high_c": 23, "temp_low_c": 18, "humidity_pct": 68,
        "rain_probability_pct": 15, "uv_index": 5,
        "general_advisory": "Pleasant and dry — excellent for outdoor activities. Light jacket for evenings.",
        "daily_variations": [
            {"condition": "Sunny",        "temp_delta": 1,  "rain_delta": -5},
            {"condition": "Partly Cloudy","temp_delta": 0,  "rain_delta": 0},
            {"condition": "Cool & Clear", "temp_delta": -1, "rain_delta": 0},
        ],
    },
    12: {
        "name": "December", "season": "Winter",
        "temp_high_c": 19, "temp_low_c": 14, "humidity_pct": 67,
        "rain_probability_pct": 10, "uv_index": 3,
        "general_advisory": "Cool and clear — layered clothing recommended. Great for outdoor exploration.",
        "daily_variations": [
            {"condition": "Clear & Cool",  "temp_delta": 0,  "rain_delta": 0},
            {"condition": "Sunny",         "temp_delta": 1,  "rain_delta": -5},
            {"condition": "Partly Cloudy", "temp_delta": -1, "rain_delta": 5},
        ],
    },
}
